### ISSUE TITLE
[Suggestion] Enlarge Buttons

### ISSUE THREAD

**Issue by Ayitaka** [labo89/TraderForPoe#15]
Widen notification to 500px, enlarge buttons by 5px each, and add 4px margin between buttons.

Note: Would also be nice to be able to customize the size of notifications/buttons/etc at some point.

Current:
![current](https://user-images.githubusercontent.com/22988712/39593037-895b2b40-4ebd-11e8-87ba-22681730d004.png)

Enlarged:
![upsized](https://user-images.githubusercontent.com/22988712/39593607-23a42f84-4ebf-11e8-8f4a-be0170ceedef.png)

It displays only a portion of the code when pasted into github as 'code' so here's a zip.

TraderForPoe\Controls\TradeItemControl.xmal:
[TradeItemControl.xmal.zip](https://github.com/labo89/TraderForPoe/files/1972091/TradeItemControl.xmal.zip)

**Comment by labo89** [comment]
I will change the layout in the layout in the future to be more dynamic.
