### ISSUE TITLE
[Bug] Sacrifice Pieces Not Registering

### ISSUE THREAD

**Issue by Ayitaka** [labo89/TraderForPoe#16]
2018/05/03 12:57:36 64586703 9b0 [INFO Client 9896] @From kcennas: Hi, I'd like to buy your 6 chaos for my 4 dawn in Bestiary.

Dawn, Midnight, Dusk, and Noon

**Comment by labo89** [comment]
I will fix this tomorrow or Saturday

**Comment by Ayitaka** [comment]
Here is a fixed TradeItem.cs, all you have to do is add the images to the resource pack (I dunno where you get the images):

[TradeItem.cs.zip](https://github.com/labo89/TraderForPoe/files/1972575/TradeItem.cs.zip)

Fixes:

`    

        public enum Currency { CHAOS, ALCHCHEMY, ALTERATION, ANCIENT, ANNULMENT, APPRENTICE_SEXTANT, ARMOUR_SCRAP, AUGMENTATION, BAUBLE, BESTIARY_ORB, BINDING_ORB, BLACKSMITH_WHETSTONE, BLESSING_CHAYULAH, BLESSING_ESH, BLESSING_TUL, BLESSING_UUL, BLESSING_XOPH, BLESSE, CHANCE, CHISEL, CHROM, DIVINE, ENGINEER, ETERNAL, EXALTED, FUSING, GEMCUTTERS, HARBINGER_ORB, HORIZON_ORB, IMPRINTED_BESTIARY, JEWELLER, JOURNEYMAN_SEXTANT, MASTER_SEXTANT, MIRROR, PORTAL, REGAL, REGRET, SCOUR, SILVER, SPLINTER_CHAYULA, SPLINTER_ESH, SPLINTER_TUL, SPLINTER_UUL, SPLINTER_XOPH, TRANSMUTE, VAAL, WISDOM, DIVINE_VESSEL, OFFERING_GODDESS, SACRIFICE_DUSK, SACRIFICE_DAWN, SACRIFICE_NOON, SACRIFICE_MIDNIGHT };

`

`    

                else if (strPrice.Contains("dawn"))
                {
                    return Currency.SACRIFICE_DAWN;
                }

                else if (strPrice.Contains("dusk"))
                {
                    return Currency.SACRIFICE_DUSK;
                }

                else if (strPrice.Contains("noon"))
                {
                    return Currency.SACRIFICE_NOON;
                }

                else if (strPrice.Contains("midnight"))
                {
                    return Currency.SACRIFICE_MIDNIGHT;
                }
`

`    

                case Currency.SACRIFICE_DAWN:
                    return new BitmapImage(new Uri("pack://application:,,,/Resources/Currency/sac_dawn.png"));
                case Currency.SACRIFICE_DUSK:
                    return new BitmapImage(new Uri("pack://application:,,,/Resources/Currency/sac_dusk.png"));
                case Currency.SACRIFICE_NOON:
                    return new BitmapImage(new Uri("pack://application:,,,/Resources/Currency/sac_noon.png"));
                case Currency.SACRIFICE_MIDNIGHT:
                    return new BitmapImage(new Uri("pack://application:,,,/Resources/Currency/sac_midnight.png"));
`
