### ISSUE TITLE
[Suggestion] A few improvements

### ISSUE THREAD

**Issue by Pegoth** [labo89/TraderForPoe#19]
I looked at the code and I recommend a code cleanup with ReSharper. And I noticed that you saved Top as X and Left as Y in the settings. It should be the other way around (_At MainWindow.xaml.cs line 488_).
```csharp
Settings.Default.WindowLocation = new System.Drawing.Point((int)this.Top, (int)this.Left);
```
Overall I like the program, but found a few possible improvements:
### Smaller improvements
- [x] Browse button for the Client.txt selection in settings (`Microsoft.Win32.OpenFileDialog`)
- [x] Pop up the settings window on first start instead of the dialog box
- [x] When buying item make the stash button non-clickable (preventing the "is it a quad stash?" message)
- [ ] When the game not in foreground hide the visible windows

### New features
- [ ] Option to grow upwards (to make it possible to place the window on the bottom right)

**Comment by labo89** [comment]
The last one is very tricky, maybe in the near future. Same with hiding.

**Comment by Pegoth** [comment]
The last one is hard yes, but the hiding is not at all. I threw together some 10sec coding.
```csharp
[DllImport("user32.dll")]
private static extern IntPtr GetForegroundWindow();

private void tick(object sender, EventArgs e)
{
	if (GetForegroundWindow() != FindWindow("POEWindowClass", "Path of Exile"))
		Hide();
	else
		Show();
}

private void starttimer()
{
	System.Windows.Threading.DispatcherTimer dispatcherTimer = new System.Windows.Threading.DispatcherTimer();
	dispatcherTimer.Tick += tick;
	dispatcherTimer.Interval = new TimeSpan(0, 0, 1);
	dispatcherTimer.Start();
}
```
