### ISSUE TITLE
Keyboard support

### ISSUE THREAD

**Issue by mortan** [labo89/TraderForPoe#2]
Hey, any plans on adding hotkey support? If you aren't currently working on it I could do some initial work.

**Comment by labo89** [comment]
Hi, for what exactly? For leaving party and visit own hideout?

**Comment by mortan** [comment]
Pretty much for all actions you can click on the overlay! :)

I regulary use the combo "invite, trade, thanks, close" on mercury trade with 4 hotkeys, so I miss this on this -otherwise- great tool!

**Comment by labo89** [comment]
How would you determine which player to invite or to close, if you have more than one notification open?

**Comment by mortan** [comment]
I'd go with a FIFO solution, first trade (aka the oldest) responds to the hotkeys.

Very useful if you get multiple whispers for the same item, I always press CTRL+2 to respond "Sorry sold" in that case.

**Comment by labo89** [comment]
That sounds nice. How would this be realized?

**Comment by Ayitaka** [comment]
If I may...

Use the current settings window and just add buttons labeled "Bind Key" at the end of each message type. 

When a user clicks a button after a message, the label of the button changes to "Press a key". 

Excluding the ESC key (so users can cancel binding a key if they press ESC), when a user presses any key (combination) it becomes a bind and anytime the notifications 'window' is in focus and a user presses a bound key (combination) the corresponding action/message is performed. After a message type is bound, the "Bind Key" button changes labels to show the key (combination) that is bound.

(i.e. Message Type: Thank you.... I click Bind Key, the button changes to Press a key... I hold CTRL key and press the number 1.... the button changes again to "CTRL 2". Thereafter, whenever a notification pops up and I press CTRL and 2 it will send the Thank you message to the top notification customer.

Bonus points for adding a checkbox to each message type for "Close notification on action", which would close the notification whenever a notification button or keybind for a message type is clicked.

**Comment by labo89** [comment]
This will not work without user32.dll. Hate this. xD

**Comment by Ayitaka** [comment]
(facepalm) 🔨
