### ISSUE TITLE
[Question] Should Settings.Default.CloseItemAfterTrade apply to ClickKickCustomer too?

### ISSUE THREAD

**Issue by Ayitaka** [labo89/TraderForPoe#22]
When I have multiple customers at the same time I cannot kick myself, I have to kick customers. I find myself closing the item immediately after kicking them so I wonder if Settings.Default.CloseItemAfterTrade should also apply to ClickKickCustomer?

**Comment by Ayitaka** [comment]
While we are on that topic, it might be nice too if the item buttons "whisper customer" and "kick customer" were switched so that kick customer was on top next to kick self.

**Comment by labo89** [comment]
Added.

**Comment by labo89** [comment]
If you are not leader the button gets useless. Whispering should be available if items are collapsed. Maybe i will add rightlick to kick.

**Comment by Ayitaka** [comment]
Ahhh I didnt think about whats available when collapsed - you are very correct that whisper should be available. Hmmm ok, it was just a thought :)  Thank you for the updates!

**Comment by labo89** [comment]
You can right click on the button now and it will kick the customer. I have removed the obsolete button.

**Comment by Ayitaka** [comment]
That's a great compromise! Excellent.
