### ISSUE TITLE
Stack msges from bottom up

### ISSUE THREAD

**Issue by Marcvz** [labo89/TraderForPoe#25]
Hi, I just started using this tool because mecurytrade is kinda buggy. But I'm missing some features that make me go back to mercurytrade.

Is it possible to make the next msg appear above the previous one?
I like to have the window at the bottom of my screen.

If someone spam whispers you, which happens a lot when you sell maps, the tool shows all the separate msges. It would be nice if you can ignore the duplicated msges or group them all under the same thingy.

**Comment by labo89** [comment]
Hey, I will correct the bug with duplicate items.
I have no proper solution for bottom placement with the current layout. Maybe I will change it in the future.

**Comment by Marcvz** [comment]
It could be as simple as a checkbox in the setting panel.
Stack top-down or bottom-up.
And place the next msg above the previous one.

Big thanks for your work and for sharing it with us. Poe would be a much lesser game without all the cool third party sites and tools!

**Comment by labo89** [comment]
The items are child elements in a stackpanel. If I add them to the top, the windows keeps resizing to the bottom and not top. If i handle this in the size changed event, it start flickering. Since I do not have a proper solution for this, I will not implement this. :)

**Comment by labo89** [comment]
I thought your first one was a bug. I realized it is a feature request. What do you mean by ignoring them? Messages from the same customer for the same item will be ignored.

**Comment by Marcvz** [comment]
Its mostly a problem with selling maps.
Maybe ignore duplicate whispers for the same map name if its white and has no quality?

**Comment by labo89** [comment]
I will add it to my list. Maybe I implement some sort of filter.
