### ISSUE TITLE
UI Suggestions

### ISSUE THREAD

**Issue by Razunter** [labo89/TraderForPoe#28]
Using this app to replace abandoned MecruryTrade, but have a big wishlist regarding UI...

1. Bigger UI. Buttons are very small and cluttered. Having to be very precise when clicking buttons isn't fun.
2. More buttons. I almost have all buttons that I need, but not quite. For example, I want "I'm in Lab" button. I use separate buttons for "thx" when buying and selling (+"sold"), so I have no space for "in lab".
3. Preview mode so I can position window when I have no incoming trades available.
4. Reversed positioning mode when new messages go up, not down.
5. Better order of buttons: Invite → **Find** → Trade → Thx → Kick...
6. Whois button could be useful sometimes.
7. Maybe option to choose custom icons for [1] & [2] buttons.

**Comment by MaT-PT** [comment]
Regarding 6., the /whois button is actually the name of the other person on the notification.
Otherwise, I agree with the rest of your suggestions.

**Comment by labo89** [comment]
Im very busy right now, but will look into it.

1. Maybe i will make size customizable.
2. One or two more custom buttons
3. Maybe a button in the settings, which sends a test whisper.
4. I have tried this. The problem is, it does flicker, since it is a stack panel.
5. The find button is not the primary search option. 
6. Whois is implemented. Click on the name.
7. Maybe maybe xD

Fell free to send me pull requests.

**Comment by Razunter** [comment]
> The find button is not the primary search option.
huh? I don't see any other options...

**Comment by labo89** [comment]
When you sell something and invite or click on the item, an overlay with the stash tab name will appear. You can hover over it and it will highlight the position. You can click on the stash button and declare it as an quad tab.

![unbenannt](https://user-images.githubusercontent.com/11984646/40995581-b0167c10-68ff-11e8-9841-0f167bf450bb.png)

**Comment by Razunter** [comment]
I didn't know that. Why this isn't mentioned anywhere?

**Comment by labo89** [comment]
Well, I am just a lazy person. xD
