### ISSUE TITLE
essences and some divination cards do not showup

### ISSUE THREAD

**Issue by Xloctis** [labo89/TraderForPoe#30]
as in title.
@xloctis_Z Hi, I would like to buy your Deafening Essence of Anguish listed for 3 chaos in Incursion (stash tab "E"; position: left 76, top 1)
will not produce trade notification

**Comment by labo89** [comment]
![image](https://user-images.githubusercontent.com/11984646/43457299-b3c0d3f4-94c6-11e8-8ff7-0a3411260142.png)

It is working here. Try and restart maybe.

**Comment by Xloctis** [comment]
after cleaning appdata does show now, what about  
@xloctis_Z Hi, I'd like to buy your 51 chaos for my 10 sacrifice set in Incursion.
??
is that also only my problem?

**Comment by labo89** [comment]
I have added a quick fix. The problem is that the currency is not implemented. If it can not parse the currency, it will only show the quantity. You can hover the mouse over and see what currency it is. I will maybe write a a complete library for currency. This should do it for now.
