### ISSUE TITLE
Stash item highlighting

### ISSUE THREAD

**Issue by Xloctis** [labo89/TraderForPoe#31]
after about 1-2 hours of using stash highlighting doesnt come up. i cant for sure say how to track it or how to reproduce but each day i have to right click on tray restart for it to help me locate items again

**Comment by labo89** [comment]
Hey, yeah. I have noticed this problem. Do you use hibernation in windows?

**Comment by Xloctis** [comment]
no, hibernation completely disabled.

**Comment by ponsu6** [comment]
also something about stash highlight i would like to suggest is that this function should be automatically highlight item when hover or click the item name in gui offer box for QoL this will help managing multiple trade at the same time doing multiple clicks or checking item name for each person will make trading hard here is my solutions

1. https://imgur.com/7u3XD1r
2. https://imgur.com/1tKmcIW


another thing is ratio when selling currency the ratio that show on offer box should base on what we offer! this way we can know if someone try to scam us when ratio is not correct as we offer

https://imgur.com/paKjIqE

**Comment by mangni** [comment]
Yes please add this stash highlighting feature!  Right now I'm considering formatting my computer just so that I can use MercuryTrade for selling (their stash grid broke after the app crashed).  Would love to use TraderForPoe for both buying and selling!  (I think it's more stable and simple to use than all the rest)

**Comment by labo89** [comment]
Hi, I don't play POE at the moment and don't develop it either.
