### ISSUE TITLE
All actions close active TraderForPoe sessions

### ISSUE THREAD

**Issue by bokanov** [labo89/TraderForPoe#40]
When I click any button on TraderForPoe, it closes. Even when I have the setting unchecked for 'Remove Item After Trade' the window still closes after I press a button for thanks or kick from party.

I am rolled back to version 1.8 that does not have this problem and it's working fine. Unchecked the setting to check for updates and seems to be OK for now.

**Comment by bokanov** [comment]
Found the setting - thanks

**Comment by bokanov** [comment]
Apparently those check boxes don't exist in 2.1

I am still back on 1.8 as clicking any button in 2.1 closes the TraderForPoE window on a Steam session

**Comment by labo89** [comment]
The check boxes are still there :)

![Anmerkung 2019-04-03 145054](https://user-images.githubusercontent.com/11984646/55480190-fc658f80-561f-11e9-99f8-c1c237392044.png)
