### ISSUE TITLE
HighDPI Scaling.

### ISSUE THREAD

**Issue by Shishiaha** [labo89/TraderForPoe#41]
Hi,

first of all, this app is the best ever for trade on PoE. Honestly, it's light and powerful.

But i have a problem with stash highlight, i play in 1080p, but my desktop is scaled by a factor of 125%. I can say to pathofexile.exe to keep the application scaling settings (and not the system one) in compatibility screen (property of .exe).

But it's not working for TraderForPoe, it always use the scaling setting of the desktop no matter what, wich is neat for buttons as they are bigger, but stash highlight is not calibrated for it, and highlight wrong location.

Could we have a scaling option (like -scalingfactor=1.0), or a manual resolution option, or just could the app work with the compatibility option of windows.

Thanks very much !

**Comment by labo89** [comment]
Hi,

here is a workaround:
Right click on TraderForPoe.exe
-> Properties 
-> Tab "Compatibility"
-> Change high DPI setting 
-> Mark the checkbox "Override high DPI scaling behavior"
-> Select "System" in drop down

I have startet a complete rework, but unfortunately, I have little time.

Cheers

**Comment by Shishiaha** [comment]
> I can say to pathofexile.exe to keep the application scaling settings (and not the system one) in compatibility screen (property of .exe).
>
>But it's not working for TraderForPoe, it always use the scaling setting of the desktop no matter what, wich is neat for buttons as they are bigger, but stash highlight is not calibrated for it, and highlight wrong location.

It's what i used for every programs, but it's not working with TraderForPoe, and only with it. This one always scale and do not listen compatibility settings.

I'd really love to make it work,this tool really is awesome, maybe someone will have an idea to force the display resolution of your tool or put a scaling argument (Like next to shortcut target).

Thanks for your help.

**Comment by labo89** [comment]
Did you select System?

I have tested it with 125 % and it is working fine.

**Comment by Shishiaha** [comment]
Yes i did. What is working for you ? My system is 125% scaled, but whatever i put for TraderForPoe make the highlight in stash out of the box or wrong (the red square is scaled). Do you have a screenshot ?

**Comment by labo89** [comment]
Path of exile will not scale. The size will stay the same. You have to prevent the scaling for TraderForPoe.

**Comment by Shishiaha** [comment]
Exactly, but i cannot do it with any compatibility option of windows.

**Comment by labo89** [comment]
Just follow the Steps. I have tested it. It work for me.
Right click on TraderForPoe.exe
-> Properties
-> Tab "Compatibility"
-> Change high DPI setting
-> Mark the checkbox "Override high DPI scaling behavior"
-> Select "System" in drop down
-> Log out

**Comment by Shishiaha** [comment]
I cleaned some registry entry, it seems to work now with system in compatibility.

If you have same problem, check registry entries in Current machine > software > Microsoft > windows NT > SidebySide
