### ISSUE TITLE
Not working with Vulkan

### ISSUE THREAD

**Issue by Petusillos** [labo89/TraderForPoe#45]
After installation of this patch:

https://www.pathofexile.com/forum/view-thread/2866812

The tool is not able to be displayed on the front if Vukan is selected (works fine if I switch to XD11)

**Comment by Versalkul** [comment]
Oh no, i was looking for a replacement because [POE-Trades-Companion has the same issue](https://github.com/lemasato/POE-Trades-Companion/issues/299)   :(

**Comment by lemasato** [comment]
Posting my message from my repo here aswell:
> Hiya, this is an issue with the game itself.  
While using Vulkan, "Windowed fullscreen" is actually 100% fullscreen and not windowed. This is an issue with their implementation, that I believe they will fix eventually. I'd recommend playing "Windowed" or reverting back to DirectX

**Comment by labo89** [comment]
See lemasatos post

**Comment by Petusillos** [comment]
> Commenting again to share a workaround for the issue: [here it is](https://www.reddit.com/r/pathofexile/comments/gseuoy/vulkan_test_technical_megathread/fs6tie9/)

Tested "POE AutoBorderless" script and now I can use Vulkan + your tool with no problem. It works like a charm. Hope GGG fix this issue. Thanks a lot for your work and your time.
