### ISSUE TITLE
[Suggestion] Show Time Since Notification Popped Up

### ISSUE THREAD

**Issue by Ayitaka** [labo89/TraderForPoe#6]
Add time since the trade offer came in to the notification panel. Using format 0-59s, or 1-59m, or 1-24h.

i.e. 25s, 15m, 2h, etc.

See attached example of where this might be placed after item name (note: stretched width of notification to 500 for this).

![tradeforpoewithtimesince](https://user-images.githubusercontent.com/22988712/39408564-3abfe698-4b8d-11e8-874e-cb2e60113de9.png)

**Comment by labo89** [comment]
Added. Thank you.

**Comment by Ayitaka** [comment]
Works perfectly.  Thank you!
