### ISSUE TITLE
[Suggestion] Make PoeForTrade Check Both Locations For Client.txt

### ISSUE THREAD

**Issue by Ayitaka** [labo89/TraderForPoe#7]
PoeForTrade currently defaults to the steam location to find Client.txt. To ensure there is no error for other users who don't use steam, on first run you should make it check for the file in both the steam directory and also in:

> C:\Program Files (x86)\Grinding Gear Games\Path of Exile\logs\Client.txt

and update the setting according to whichever it finds first. I would check the above location first because in the case where they have both installed for some reason I think its reasonable to assume they probably use the stand-alone version (?).

**Comment by labo89** [comment]
Added
