### ISSUE TITLE
[Bug] Master/Journeyman S(ex)tants come after (Ex)alted in TradeItem.cs

### ISSUE THREAD

**Issue by Ayitaka** [labo89/TraderForPoe#9]
Need to re position Journeyman and Master Sextants to be before Exalted in regex checks in TradeForPoe/Classes/TradeItem.cs

(I just put them up by Apprentice Sextants)

![mastersextantasexalt](https://user-images.githubusercontent.com/22988712/39414478-b6bf48ce-4bec-11e8-8be0-389ad706ba12.png)

**Comment by labo89** [comment]
Fixed
